name: Waka Readme

on:
  schedule:
    # Runs at 12am each day
    - cron: '00 00 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: True
          SHOW_LINES_OF_CODE: True
          SHOW_TOTAL_CODE_TIME: True
          SHOW_PROFILE_VIEWS: True
          SHOW_DAYS_OF_WEEK: False
          SHOW_OS: False
          SHOW_EDITORS: False
          SHOW_LOC_CHART: True
          SYMBOL_VERSION: 1
